### ISSUE TITLE
Symbols from shared libraries (open question)

### ISSUE THREAD

**Issue by mothran** [elfmaster/ecfs#14]
What is the best way to either access (or create accessors) for symbols in the modules for a given ECFS file?  I know I can use get_local_symbols() to get the symbols for the primary binary but how should we make something that can resolve symbols over all modules within the binary?

**Comment by elfmaster** [comment]
All of the dynamic symbols are the ones that you want, they are the symbols for shared library functions. These are stored in a public vector after the class is instantiated, or after get_dynamic_symbols() are invoked. So its simply a matter of accessing that vector. You've not seen the latest code, but there are quite a few updates.

```
std::vector <ecfs_sym_t> m_dynsym;
```

**Comment by elfmaster** [comment]
Although that vector is in the code you have access too already, so the code updates are not relevant in relation to the dynamic symbols, other then the fact that in the new code there is more than one way to instantiate an ecfs object.

**Comment by mothran** [comment]
herp derp, I just was reading through ecfs core code and found that.  I ended up making a bit of different way of accessing that vector and making get_ and gen_ function for dyn symbols in the oop branch.  I guess I did not see that the vector was public.  Thanks!

**Comment by mothran** [comment]
Oh they were not public, ok I will push my most recent update to parker/oop_fixes and see if you think its a good module for accessing that data.

**Comment by elfmaster** [comment]
Hey bro. Yeah, I carefully viewed your changes last week (Not the latest ones). I actually have have an email partially complete because there were some changes you had made that dissented from the design model I was moving towards. Also a bug was introduced into get_prstatus (well in gen_prstatus now I think). I will get this email to you soon, that way we can sync up on the overall design before we move forward. No worries though, we can get it all figured out and in sync with each other. I believe my computer time is about up for the day, I'll see you next Friday for sure. BTW, nice find with that stack unwinding issue with ecfs, I believe there are going to be a number of issues that arise like that.

**Comment by mothran** [comment]
Yeah I actually have his some interesting bugs around local symbols that I would like to go over once I make simple test cases as well.  Yeah I would would like to sync up about design choices for sure because I am blazing ahead rewriting libecfs_oop how I want to use it as I go, while making a tool that uses it.

**Comment by elfmaster** [comment]
Yeah no worries man, we have git to handle various branches. About symbols: There are also some problems even with dynamic symbols btw... so beware. Not bugs, but the inability to properly resolve certain ones sometimes... I have some ideas on how to make this better of course, but alas! lack of time prevented me to fix upon discovery. As for the local symbols go... definately enlighten me to any bugs you know of in that area too. I won't probably be on much until I get back on Friday though. Also the stack unwinding bug is a concern, I have a good idea as to where it originates from. That's a pretty serious bug that needs fixing, although I don't think its always present, but I can't remember the last time I validated the stack. Anyway I'm getting carried away already on the computer, I gotta run! Have a great weekend.
